{% set name = "flexmod" %}
{% set version = "0.1.2" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5558a13177c76299d6cf068ecb26f0bbc2c91696d5fc68726dce6648dfb4564

build:
  number: 1
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - flexmod
  commands:
    - pip check

about:
  home: https://github.com/haochuanwei/flexmod
  license: MIT
  license_file: LICENSE
  summary: A python module for other modules to allow flexible (yet not error-prone) configuration.
  dev_url: https://github.com/haochuanwei/flexmod

extra:
  recipe-maintainers:
    - haochuanwei
